apiVersion: serving.knative.dev/v1
kind: Service
metadata:
   name: openllm
   namespace: awakenrealms
spec:
   template:
     spec:
       containers:
         - image: gcr.io/awakenrealms/openllm
           ports:
             - containerPort: 3000